happinesspackets/messaging/urls.py
from __future__ import unicode_literals

from django.urls import path, re_path

from .views import (StartView, MessageSendView, MessageSenderConfirmationSentView, MessageSenderConfirmationView,
                    MessageSenderConfirmedView, MessageRecipientMessageUpdate, FaqView, ArchiveView, BlacklistEmailView)

app_name = "messaging"

urlpatterns = [
    path('', StartView.as_view(), name='start'),
    path('faq/', FaqView.as_view(), name='faq'),
    path('archive/', ArchiveView.as_view(), name='archive'),
    re_path(r'^blacklist-email/(?P<email>[\w\.@\+-]+)/(?P<digest>\w+)/$', BlacklistEmailView.as_view(), name='blacklist_email'),
    path('send/', MessageSendView.as_view(), name='send'),
    path('send/confirmation-sent/', MessageSenderConfirmationSentView.as_view(), name='sender_confirmation_sent'),
    re_path(r'^send/confirmation/(?P<identifier>[\w-]+)/(?P<token>[\w-]+)/$', MessageSenderConfirmationView.as_view(), name='sender_confirm'),
    path('send/confirmed/', MessageSenderConfirmedView.as_view(), name='sender_confirmed'),
    re_path(r'^recipient/(?P<identifier>[\w-]+)/(?P<token>[\w-]+)/$', MessageRecipientMessageUpdate.as_view(), name='recipient_message_update'),
]

oslove/urls.py
from __future__ import unicode_literals

import django
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('oslove.messaging.urls', namespace="messaging")),
]

if settings.ADMIN_ENABLED or settings.DEBUG:
    urlpatterns.append(url(r'^drunken-octo-lama/', include(admin.site.urls)))

if settings.DEBUG:
    urlpatterns.append(url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}))

oslove/messaging/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import logging

from model_utils import Choices

from oslove.utils.misc import readable_random_token
from django.db import models
from model_utils.models import TimeStampedModel

logger = logging.getLogger(__name__)


class Message(TimeStampedModel):
    STATUS = Choices(
        'pending_sender_confirmation',
        'sent',
        'read',
    )

    identifier = models.CharField(max_length=255, db_index=True)
    status = models.CharField(choices=STATUS, default=STATUS.pending_sender_confirmation, max_length=255)

    sender_name = models.CharField(max_length=255)
    sender_email = models.EmailField()
    sender_email_token = models.CharField(max_length=255, db_index=True)
    sender_ip = models.GenericIPAddressField()

    recipient_name = models.CharField(max_length=255)
    recipient_email = models.EmailField()

    message = models.TextField()

    sender_named = models.BooleanField(default=False)
    sender_approved_public = models.BooleanField(default=False)
    sender_approved_public_named = models.BooleanField(default=False)
    recipient_approved_public = models.BooleanField(default=False)
    recipient_approved_public_named = models.BooleanField(default=False)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.pk or force_insert:
            self.identifier = readable_random_token(alphanumeric=True)
            while Message.objects.filter(identifier=self.identifier).count():
                self.identifier = readable_random_token(alphanumeric=True)  # pragma: no cover
        return super(Message, self).save(force_insert, force_update, using, update_fields)

happinesspackets/messaging/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import logging
from datetime import timedelta

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, HTML
from django import forms
from django.conf import settings
from django.urls import reverse
from django.db.models import Q
from django.utils import timezone

from .models import Message, strip_email

logger = logging.getLogger(__name__)


def validate_email(email):
    timeframe = timezone.now() - timedelta(hours=24)
    stripped_email = strip_email(email)
    recent_message_count = Message.objects.filter(Q(sender_email_stripped=stripped_email) | Q(recipient_email_stripped=stripped_email), created__gte=timeframe).count()
    if recent_message_count > settings.MAX_MESSAGES:
        raise forms.ValidationError("We can't send emails to this address at this time. You can try again in 24 hours.")


class MessageSendForm(forms.ModelForm):
    hp = forms.CharField(label="do not fill", required=False)

    class Meta:
        model = Message
        fields = ['sender_name', 'sender_email', 'recipient_name', 'recipient_email', 'message',
                  'sender_named', 'sender_approved_public', 'sender_approved_public_named']

    def __init__(self, *args, **kwargs):
        super(MessageSendForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-8'

        self.fields['sender_name'].label = 'Name'
        self.fields['sender_email'].label = 'Email'
        self.fields['sender_email'].help_text = "We'll send you a confirmation link before sending your message out."
        self.fields['sender_email'].validators = [validate_email]
        self.fields['recipient_name'].label = 'Name'
        self.fields['recipient_email'].label = 'Email'
        self.fields['recipient_email'].validators = [validate_email]
        self.fields['message'].help_text = 'Writer\'s block? Check out our <a href="%s">happiness archive</a>.' % reverse('messaging:archive')
        self.fields['sender_named'].label = 'I agree to share my name and email address with the recipient.'
        self.fields['sender_approved_public'].label = "I agree to publish this message and display it publicly in the Happiness Archive."
        self.fields['sender_approved_public_named'].label = "... and I agree to display our names publicly too."
        self.fields['sender_approved_public_named'].help_text = "Note: We only publish information if both the sender and the recipients agree."

        self.helper.layout = Layout(
            Fieldset('This Happiness Packet is from...', 'sender_name', 'sender_email', 'hp'),
            Fieldset("Send this Happiness Packet to...", 'recipient_name', 'recipient_email'),
            Fieldset("Your message is...", 'message'),
            Fieldset("Privacy and permissions", 'sender_named', 'sender_approved_public', 'sender_approved_public_named'),
            HTML("<br>"),
            Submit('submit', 'Send some happiness', css_class='btn-lg centered'),
        )

    def clean(self):
        super(MessageSendForm, self).clean()
        if self.cleaned_data.get('hp'):
            raise forms.ValidationError('')
        if self.cleaned_data.get('sender_approved_public_named') and not self.cleaned_data.get('sender_approved_public'):
            self.add_error('sender_approved_public_named', "If you want us to publish the message including your names, "
                                                           "you must also check 'I agree to publish this message and"
                                                           "display it publicly in the Happiness Archive'")


class MessageRecipientForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['recipient_approved_public', 'recipient_approved_public_named']

    def __init__(self, *args, **kwargs):
        super(MessageRecipientForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-8'

        self.fields['recipient_approved_public'].label = "I agree to publish this message and display it publicly in the Happiness Archive."
        self.fields['recipient_approved_public_named'].label = "... and I agree to display our names publicly too."
        self.fields['recipient_approved_public_named'].help_text = "Note: We only publish information if both the sender and the recipients agree."

        self.helper.layout = Layout(
            Fieldset("Privacy and permissions", 'recipient_approved_public', 'recipient_approved_public_named'),
            HTML("<br>"),
            Submit('submit', 'Save privacy choices', css_class='btn-lg centered'),
        )

    def clean(self):
        super(MessageRecipientForm, self).clean()
        if self.cleaned_data.get('recipient_approved_public_named') and not self.cleaned_data.get('recipient_approved_public'):
            self.add_error('recipient_approved_public_named', "If you want us to publish the message including your "
                                                              "names, you must also check 'I agree to publish this "
                                                              "message and display it publicly in the Happiness "
                                                              "Archive.'")

oslove/messaging/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import logging

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, HTML
from django import forms

from oslove.messaging.models import Message

logger = logging.getLogger(__name__)


class MessageSendForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['sender_name', 'sender_email', 'recipient_name', 'recipient_email', 'message',
                  'sender_named', 'sender_approved_public', 'sender_approved_public_named']

    def __init__(self, *args, **kwargs):
        super(MessageSendForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-8'

        self.fields['sender_name'].label = 'Name'
        self.fields['sender_email'].label = 'Email'
        self.fields['sender_email'].help_text = "We'll send you a confirmation link before sending your message out."
        self.fields['recipient_name'].label = 'Name'
        self.fields['recipient_email'].label = 'Email'
        self.fields['message'].help_text = 'Writer\'s block? Check out our <a href="#">message inspiration</a>.'
        self.fields['sender_named'].label = 'You can tell the recipient my name and email address.'
        self.fields['sender_approved_public'].label = "I'm OK with you publishing this message publicly"
        self.fields['sender_approved_public_named'].label = "...and you can even include our names publicly."

        self.helper.layout = Layout(
            Fieldset('This message is from...', 'sender_name', 'sender_email'),
            Fieldset("You're sending some love to...", 'recipient_name', 'recipient_email'),
            Fieldset("Your message is...", 'message'),
            Fieldset("Privacy choices", 'sender_named', 'sender_approved_public', 'sender_approved_public_named'),
            HTML("<br>"),
            Submit('submit', 'Send some love', css_class='btn-lg btn-block'),
        )

    def clean(self):
        super(MessageSendForm, self).clean()
        if self.cleaned_data.get('sender_approved_public_named') and not self.cleaned_data.get('sender_approved_public'):
            self.add_error('sender_approved_public_named', "If you want us to publish the message including your name, "
                                                           "you must also check 'I'm OK with you publishing this "
                                                           "message publicly'")

happinesspackets/messaging/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import logging

from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, Http404
from django.utils.crypto import salted_hmac, constant_time_compare
from django.utils.decorators import method_decorator
from django.utils.html import format_html
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, TemplateView, UpdateView, ListView

from .forms import MessageSendForm, MessageRecipientForm
from .models import Message, BLACKLIST_HMAC_SALT, BlacklistedEmail, strip_email

logger = logging.getLogger(__name__)


class ArchiveListView(ListView):
    model = Message

    def get_queryset(self):
        queryset = super(ArchiveListView, self).get_queryset()
        return queryset.filter(sender_approved_public=True, recipient_approved_public=True, admin_approved_public=True)


class StartView(ArchiveListView):
    template_name = 'messaging/start.html'

    def get_queryset(self):
        return super(StartView, self).get_queryset().order_by('?')[:2]


class FaqView(TemplateView):
    template_name = 'messaging/faq.html'


class ArchiveView(ArchiveListView):
    template_name = 'messaging/archive.html'


class BlacklistEmail(object):
    pass


class BlacklistEmailView(TemplateView):
    success_url = reverse_lazy('messaging:start')
    template_name = 'messaging/blacklist_email.html'

    def get_email(self):
        expected_digest = salted_hmac(BLACKLIST_HMAC_SALT, self.kwargs['email'])
        if not constant_time_compare(expected_digest.hexdigest(), self.kwargs['digest']):
            raise Http404
        return self.kwargs['email']

    def get_context_data(self, **kwargs):
        context = super(BlacklistEmailView, self).get_context_data(**kwargs)
        context['email'] = self.get_email()
        return context

    def post(self, request, *args, **kwargs):
        email = self.get_email()
        stripped_email = strip_email(email)
        BlacklistedEmail.objects.create(email=email, stripped_email=stripped_email, confirmation_ip=self.request.META['REMOTE_ADDR'])
        message = format_html("We've blacklisted your address and will never email <em>{0}</em> again. Sorry to have bothered you!", email)
        messages.success(self.request, message)
        return HttpResponseRedirect(self.success_url)


class MessageSendView(FormView):
    template_name = 'messaging/message_send_form.html'
    form_class = MessageSendForm

    @method_decorator(sensitive_post_parameters('message'))
    def dispatch(self, *args, **kwargs):
        return super(MessageSendView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        message = form.save(commit=False)
        message.sender_ip = self.request.META['REMOTE_ADDR']
        message.save()
        message.send_sender_confirmation(self.request.is_secure(), self.request.get_host())
        return HttpResponseRedirect(reverse('messaging:sender_confirmation_sent'))


class MessageSenderConfirmationSentView(TemplateView):
    template_name = 'messaging/message_sender_confirmation_sent.html'


class MessageSenderConfirmationView(TemplateView):
    template_name = 'messaging/message_sender_confirmation_failed.html'

    def get(self, request, *args, **kwargs):
        try:
            message = Message.objects.get(identifier=kwargs['identifier'], sender_email_token=kwargs['token'])
        except Message.DoesNotExist:
            return self.render_to_response({'not_found': True})

        if message.status != Message.STATUS.pending_sender_confirmation:
            return self.render_to_response({'already_confirmed': True})

        message.send_to_recipient(self.request.is_secure(), self.request.get_host())
        return HttpResponseRedirect(reverse('messaging:sender_confirmed'))


class MessageSenderConfirmedView(TemplateView):
    template_name = 'messaging/message_sender_confirmed.html'


class MessageRecipientMessageUpdate(UpdateView):
    model = Message
    form_class = MessageRecipientForm
    template_name = 'messaging/message_recipient_form.html'
    slug_field = 'identifier'
    slug_url_kwarg = 'identifier'

    def get_queryset(self):
        message = super(MessageRecipientMessageUpdate, self).get_queryset()
        valid_status = [Message.STATUS.sent, Message.STATUS.read]
        return message.filter(recipient_email_token=self.kwargs['token'], status__in=valid_status)

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Your choices have been saved.")
        return HttpResponseRedirect(self.request.path)

templates/messaging/_message_list.html
{% for message in message_list %}
    <h4>
        {% if message.sender_approved_public_named and message.recipient_approved_public_named %}
            From {{ message.sender_name }} to {{ message.recipient_name }}
        {% else %}
            Anonymous message
        {% endif %}
    </h4>
    <blockquote>
        {{ message.message|linebreaksbr }}
    </blockquote>
{% endfor %}

templates/messaging/_message_list_more_content.html
{% for message in message_list %}
    {% if forloop.counter > 4 %}
    <h4>
        {% if message.sender_approved_public_named and message.recipient_approved_public_named %}
            From {{ message.sender_name }} to {{ message.recipient_name }}
        {% else %}
            Anonymous message
        {% endif %}
    </h4>
    <blockquote>
        {{ message.message|linebreaksbr }}
    </blockquote>
    {% endif %}
{% endfor %}

templates/messaging/archive.html
{% extends 'base.html' %}
{% block extra_head %}<title>Happiness Archive</title>{% endblock %}

{% block content %}

    <div class="page-header">
        <h2>Happiness Archive</h2>
    </div>

    <p>
        When you send a Happiness Packet, you can agree to display your message publicly on
        this website. If both sender and recipient select this option, the message is published
        on this page as a part of our Happiness Archive.
    </p>

    {% include 'messaging/_message_list.html' %}

{% endblock content %}

templates/messaging/blacklist_email.html
{% extends 'base.html' %}

{% block content %}

    <div class="page-header">
        <h2>Block e-mail address</h2>
    </div>

    <p>
        If you don't want to receive e-mail messages to <em>{{ email }}</em> ever again, confirm by
        clicking the <b>Never email me again</b> button. If anyone tries to use this email address
        for a sender or recipient, we will silently discard the email.
    </p>

    <p>
        You might still receive Happiness Packets that were already sent before you blocked
        your email address.
    </p>

    <form method="post" >{% csrf_token %}
        <input type="submit" name="submit" value="Never email me again" class="btn btn-primary btn-lg centered" id="submit-id-submit">
    </form>

{% endblock content %}

templates/messaging/example_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="page-header">
        <h2>Voorbeeldpagina</h2>
    </div>

    {% crispy form %}
{% endblock content %}

templates/messaging/faq.html
{% extends 'base.html' %}

{% block extra_head %}<title>FAQ-(Frequently Asked Questions)</title>{% endblock %}

{% block content %}
<div id="faq">
    <div class="page-header">
        <h2>FAQ-(Frequently Asked Questions)</h2>
    </div>

    <h3>Who made this and why?</h3>
    <p>
        The Open-Source Happiness Packets project was created by <a href="https://twitter.com/mxsash">Sasha Romijn</a> and
        <a href="https://twitter.com/thatdocslady">Mikey Ariel</a> in March 2016.
        The idea came about while we were building our
        <a href="https://2016.djangocon.eu/speakers/13">Healthy Minds in a Healthy Community</a> presentation
        for Djangocon Europe 2016. One of the issues we wanted to address in the presentation was that many
        people are unaware of how loved, appreciated, or admired they are by their peers, since our culture seems
        to discourage positive feedback and amplify negative feedback. With this project, we wanted to provide a platform
        for people to send positive feedback, thanks, or just a kind word to their peers, with hope to make it
        easier and more acceptable for people to spread happiness, gratitude and appreciation in open-source communities.
    </p>

    <h3>Isn't it weird to send these notes to other people?</h3>
    <p>
        Many of us come from a culture where it's sometimes more acceptable to complain about the negative than to
        acknowledge the positive things. Therefore, it might feel a little awkward to communicate positive feedback
        directly to others. However, in our personal experience, once you take that first step, any awkwardness
        is quickly replaced by feeling good about helping someone else feel good.
    </p>

    <h3>Can I send anything I want?</h3>
    <p>
        We don't screen the content of messages. However, all messages must meet the
        <a href="https://www.djangoproject.com/conduct/">Django Project Code of Conduct</a>.
        Notably, harassment, insults and other exclusionary behavior are never acceptable.
    </p>
    <p>
        Violations of this can result in blocking you from using the service. Your message might also be shared with
        the Django Code of Conduct committee, who reserve the right to take further action of their own. If you're a member
        of another open-source community, your message might be shared with any code of conduct committee or similar group
        from that community.
    </p>

    <h3>Should I reply when I get a Happiness Packet from someone?</h3>
    <p>
        You are under no obligation to respond to the sender of the Happiness Packet. But if you are inspired by what
        you received, you are welcome to respond or send your own Happiness Packet. We always encourage sending more
        messages, but only if they are sincere.
    </p>
    <p>
        Note: if the sender selected to remain anonymous, you cannot reply to their message.
    </p>

    <h3>Are my Happiness Packets private?</h3>
    <p>
        By default, we only send your message with the recipient. They will get an e-mail with your message
        and can view it online. We only share your name and email address with the recipient if you choose this option.
        We may analyse messages and their metadata for statistical analysis.
    </p>
    <p>
        In case of suspected abuse or Code of Conduct violations, the service administrators might view and read
        your message to determine further processing.
    </p>

    <h3>What happens if I choose to display my message publicly?</h3>
    <p>
        If both the sender and the recipient of the message agree to publish the message on the website,
        the message will be displayed in the <a href="{% url 'messaging:archive' %}">Happiness Archive</a>.
        We encourage you to share your messages with the community,
        but the choice is yours and you are not obligated to choose this option if you do not feel comfortable with it.
        You can also choose to publish the message but keep the sender and recipient names private.
    </p>
    <p>
        Note: we cannot modify the content of the message after it is sent, so if the message includes personally-identifying
        information or references to third parties, they will be published even if you choose to hide the sender and
        recipient names.
    </p>

    <h3>I received an abusive message, what should I do?</h3>
    <p>
        Please report this to <a href="mailto:info@happinesspackets.io">info@happinesspackets.io</a>, preferably by
        forwarding the original email that contains the message.
    </p>

    <h3>I don't want to receive any email from you</h3>
    <p>
        Every email we sent includes a link to stop receiving all future e-mail messages. If you follow the link
        and confirm, your email address will not be able to be used anywhere on the site.
        Note: if you select to block your email address, you will not be able to send Happiness Packets yourself.
    </p>
</div>
{% endblock content %}

templates/messaging/message_recipient_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="page-header">
        <h2>You received an Open-Source Happiness Packet!</h2>
    </div>

    <p>
        {% if message.sender_named %}
            You received a Happiness Packet from {{ message.sender_name }} ({{ message.sender_email }}).
        {% else %}
            The sender of this message asked to remain anonymous.
        {% endif %}
        Your Happiness Packet contains:
        </p>

    <blockquote>{{ message.message|linebreaksbr }}</blockquote>

    {% crispy form %}
{% endblock content %}

templates/messaging/message_send_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="page-header">
        <h2>Send a happiness packet to someone!</h2>
    </div>

    {% crispy form %}
{% endblock content %}

templates/messaging/message_sender_confirmation_failed.html
{% extends 'base.html' %}

{% block content %}

    <div class="page-header">
        <h2>Link not valid</h2>
    </div>

    {% if not_found %}
        <div class="alert alert-danger">
            We couldn't find this message. Make sure that the URL is complete.
        </div>
    {% elif already_confirmed %}
        <div class="alert alert-info">
            You already confirmed this message.
        </div>
    {% endif %}

{% endblock content %}

templates/messaging/message_sender_confirmation_sent.html
{% extends 'base.html' %}

{% block content %}

    <div class="page-header">
        <h2>Check your email</h2>
    </div>

    <p>
        We sent you a confirmation link to your email address. Follow the link to finalize sending your message.
    </p>

{% endblock content %}

templates/messaging/message_sender_confirmed.html
{% extends 'base.html' %}

{% block content %}

    <div class="page-header">
        <h2>Happiness Packet sent</h2>
    </div>

    <div class="alert alert-success">
        Your Happiness Packet is on the way to the recipient. Have a happy day!
    </div>

{% endblock content %}

templates/messaging/recipient_mail.html
{% extends 'base_email.html' %}

{% block content %}

<p>Hello {{ message.recipient_name }}!</p>

<p>
    You just received a Happiness Packet{% if message.sender_named %} from {{ message.sender_name }} ({{ message.sender_email }}){% endif %}!
    {% if not message.sender_named %}The sender asked to remain anonymous.{% endif %}
</p>

<p>
    If this is the first time you've heard about Happiness Packets, check out
    <a href="{{ protocol }}://{{ domain }}/" style="color: #F64747;">our website</a>.
    In short, Happiness Packets are positivity messages that open-source contributors can send to each other
    anonymously and confidentially. By sending Happiness Packets, we hope to create an atmosphere where
    positive feedback is amplified and accepted more than negative feedback.
</p>

<p>Your Happiness Packet contains:</p>

<p><em>{{ message.message|linebreaksbr }}</em></p>

<p>
    If you and the sender of the Happiness Packet both agree, we'd love to publish the message to our
    <a href="{{ protocol }}://{{ domain }}{% url 'messaging:archive' %}" style="color: #F64747;">Happiness Archive</a>
    to inspire others from the community.
</p>

<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'messaging:recipient_message_update' identifier=message.identifier token=message.recipient_email_token %}" role="button" style="display: inline-block; background: #F64747;color: white;text-transform: uppercase;padding: 0.9em 1.3em;text-decoration: none;border-radius: 6px">Set publishing permissions</a>
</p>

<p>This is entirely optional, we respect your privacy and only publish messages if both the sender and recipient agree.</p>

<p>Have a happy day!</p>
{% endblock %}

templates/messaging/sender_confirmation_mail.html
{% extends 'base_email.html' %}

{% block content %}

<p>Hello {{ message.sender_name }}!</p>

<p>
    You just requested to send a Happiness Packet to {{ message.recipient_name }}.
</p>

<p>
    Your message reads: 
</p>

<p><em>{{ message.message|linebreaksbr }}</em></p>

<p>
    To confirm and send your message, click or copy this link to a web browser:
</p>

<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'messaging:sender_confirm' identifier=message.identifier token=message.sender_email_token %}" role="button" style="display: inline-block; background: #F64747;color: white;text-transform: uppercase;padding: 0.9em 1.3em;text-decoration: none;border-radius: 6px">Yes! Please send my happiness packet</a>
</p>

<p>
    Important: The message content cannot be modified after you confirm.
    If you changed your mind, simply ignore this message and do not follow the link.
    Your message will be deleted from our database and won't be sent.
</p>

<p>
    Thanks for sharing some happiness!
</p>

{% endblock %}

templates/messaging/start.html
{% extends 'base.html' %}

{% block extra_head %}<title>Fedora Happiness Packets</title>{% endblock %}

{% block content %}

    <div class="page-header">
        <h2>What are Fedora Happiness Packets?</h2>
    </div>

    <p class="lead">
        People are generally much more loved than they think they are. Especially when things don't go according to
        plan, other people almost never think as harshly of you as you might think of yourself. It's easy for us to
        complain when bad things happen, and yet we're often fairly silent when things are good. Open-source communities
        are no different, especially when our main communication channels are textual and virtual.
    </p>

    <p>
        The feeling that you made a difference, that your work matters and has value, and that the people
        you work with are happy to work with you, is an awesome feeling. With Fedora Happiness Packets, we're
        trying to spread that feeling.
    </p>

    <p class="text-center">
        <a class="btn btn-primary btn-lg btn-responsive" href="{% url 'messaging:send' %}" role="button">Send some happiness now! <img class="emoji" src="static/images/emoji/loveletter.png" alt="💌" title="Love letter" aria-label="Emoji: Love letter"></a>
    </p>

    <h2>How does it work?</h2>
    <p>
        Openly expressing appreciation, gratitude, or happiness to other people can be difficult. This is especially
        true when you don't know them very well. Many of us come from cultures in which people are not open by default
        about such feelings, and naturally feel uncomfortable or even creepy to share them.
    </p>
    <p>
        Fedora Happiness Packets is a very simple platform to anonymously reach out to the people that you
        appreciate or to whom you are thankful in your open-source community. Your message can be sent anonymously
        if you feel uncomfortable to share your name with the recipient. Of course, we encourage you to share your name,
        but it's completely optional!
    </p>

    <h3>Happiness Archive</h3>
    <p>
        If both the sender and the recipient agree, we can
        <a href="{% url 'messaging:archive' %}">publish the Happiness Packet</a> on the website.
        We hope to build an archive of open-source happiness that communities can draw inspiration from.
    </p><p>
        As an example, here are two random messages from our archive:
    </p>

    {% include 'messaging/_message_list.html' %}

    <p class="text-center">
        <a class="btn btn-primary btn-lg btn-responsive" href="{% url 'messaging:send' %}" role="button">Send some happiness now! <img class="emoji" src="static/images/emoji/loveletter.png" alt="💌" title="Love letter" aria-label="Emoji: Love letter"></a>
    </p>

{% endblock content %}