happinesspackets/messaging/urls.py
from __future__ import unicode_literals

from django.urls import path, re_path

from .views import (StartView, MessageSendView, MessageSenderConfirmationSentView, MessageSenderConfirmationView,
                    MessageSenderConfirmedView, MessageRecipientMessageUpdate, FaqView, ArchiveView, BlacklistEmailView)

app_name = "messaging"

urlpatterns = [
    path('', StartView.as_view(), name='start'),
    path('faq/', FaqView.as_view(), name='faq'),
    path('archive/', ArchiveView.as_view(), name='archive'),
    re_path(r'^blacklist-email/(?P<email>[\w\.@\+-]+)/(?P<digest>\w+)/$', BlacklistEmailView.as_view(), name='blacklist_email'),
    path('send/', MessageSendView.as_view(), name='send'),
    path('send/confirmation-sent/', MessageSenderConfirmationSentView.as_view(), name='sender_confirmation_sent'),
    re_path(r'^send/confirmation/(?P<identifier>[\w-]+)/(?P<token>[\w-]+)/$', MessageSenderConfirmationView.as_view(), name='sender_confirm'),
    path('send/confirmed/', MessageSenderConfirmedView.as_view(), name='sender_confirmed'),
    re_path(r'^recipient/(?P<identifier>[\w-]+)/(?P<token>[\w-]+)/$', MessageRecipientMessageUpdate.as_view(), name='recipient_message_update'),
]

oslove/urls.py
from __future__ import unicode_literals

import django
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('oslove.messaging.urls', namespace="messaging")),
]

if settings.ADMIN_ENABLED or settings.DEBUG:
    urlpatterns.append(url(r'^drunken-octo-lama/', include(admin.site.urls)))

if settings.DEBUG:
    urlpatterns.append(url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Open-source Happiness Packets</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic|Roboto:400,300,300italic,400italic,700,700italic&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/datepicker.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'images/favicon.ico' %}" rel="icon" type="image/x-icon">

    <!--[if lt IE 8]>
        <link href="{% static 'css/bootstrap-ie7.css' %}" rel="stylesheet">
    <![endif]-->
    {% block extra_head %}{% endblock %}
</head>

<body>
    <aside>
        <div class="sidebar">
            {% url 'messaging:start' as url %}
            <a href="{{ url }}"><img src="{% static 'images/logo.png' %}" alt="Open-Source Happiness Packets" class="logo"/></a>
            <ul class="nav nav-stacked">
                {% url 'messaging:send' as url %}
                <li role="presentation" {% if url in request.path %}class="active"{% endif %}><a href="{{ url }}">Send some happiness!</a></li>
                {% url 'messaging:start' as url %}
                <li role="presentation" {% if url in request.path %}class="active"{% endif %}><a href="{{ url }}">What are Happiness Packets?</a></li>
                {% url 'messaging:faq' as url %}
                <li role="presentation" {% if url in request.path %}class="active"{% endif %}><a href="{{ url }}">FAQ</a></li>
                {% url 'messaging:archive' as url %}
                <li role="presentation" {% if url in request.path %}class="active"{% endif %}><a href="{{ url }}">Happiness Archive</a></li>
            </ul>
        </div>
    </aside>
    <main>
        <div class="container">
            <div class="row content">
                <div class="col-md-10">
                    {% for django_message in messages %}
                        <br>
                        <div class="alert {% if django_message.tags %} alert-{{ django_message.tags }}{% endif %}">
                            {{ django_message }}
                        </div>
                    {% endfor %}
                    {% block content %}{% endblock %}
                </div>
            </div>
            <footer class="col-md-10"><small>
                <hr>
                <a href="https://twitter.com/happinesspacket" class="twitter-follow-button" data-show-count="false" data-size="large" data-dnt="true">Follow @happinesspacket</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                <br>
                Open-Source Happiness Packets is an
                <a href="https://github.com/mxsasha/happinesspackets/">open-source project</a> by
                <a href="https://twitter.com/mxsash">Sasha Romijn</a> and
                <a href="https://twitter.com/thatdocslady">Mikey Ariel</a>.
                <br>
                Design and artwork by <a href="https://twitter.com/olasitarska">Ola Sitarska</a>.
                <br>
                Need help? <a href="mailto:info@happinesspackets.io">info@happinesspackets.io</a>
                <img class="emoji" src="{% static 'images/emoji/loveletter.png' %}" alt="💌" title="Love letter" aria-label="Emoji: Love letter" style="vertical-align: text-bottom">

            </small></footer>
        </div>
    </main>
</body>
</html>

templates/base_email.html
<!DOCTYPE html>
<html lang="nl">
<head>
    <title>Open-Source Happiness Packets</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic|Roboto:400,300,300italic,400italic,700,700italic&subset=latin,latin-ext" rel="stylesheet" type="text/css">
</head>

<body style="background-color: #F23030;font-family: 'Roboto', sans-serif;font-size: 16px;line-height: 1.8em;">
    <div style="text-align: center;padding: 20px;">
        <img src="cid:logo.png@happinesspackets.io" alt="Open-source Happiness Packets" style="max-width: 400px; padding: 30px">
    </div>
    <div style="margin: auto;background-color: white;max-width: 600px;padding: 30px">
        {% block content %}{% endblock %}
        <footer style="line-height: 1.2em;"><small>
            <hr>
            <p>
                Open-source happiness packets is an
                <a href="https://github.com/erikr/happinesspackets/" style="color: #F64747;">open-source project</a> by
                <a href="https://twitter.com/mxsash" style="color: #F64747;">Sasha Romijn</a> and
                <a href="https://twitter.com/thatdocslady" style="color: #F64747;">Mikey Ariel</a>.
                Design and artwork by <a href="https://twitter.com/olasitarska" style="color: #F64747;">Ola Sitarska</a>.
                <br>
                Need help? <a href="mailto:info@happinesspackets.io" style="color: #F64747;">info@happinesspackets.io</a>
            </p>
            <p>
                Never want to receive email from us again?<br>
                <a href="{{ protocol }}://{{ domain }}{{ blacklist_url }}"  style="color: #F64747;">Block {{ recipient }}</a>
            </p>
        </small></footer>
    </div>
    <br><br>
</body>
</html>